### ISSUE TITLE
ERROR failed to download from https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-1.21.31.04.zip

### ISSUE THREAD

**Issue by unicaap** [itzg/docker-minecraft-bedrock-server#467] opened 2024-10-06 14:27 UTC
I am getting this error:

bds_1  | Looking up latest version...
bds_1  | Downloading Bedrock server version 1.21.31.04 ...
bds_1  | curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
bds_1  | ERROR failed to download from https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-1.21.31.04.zip

Is there something wrong with the url address?

**Comment by itzg** [comment] 2024-10-06 14:29
Duplicate of the pinned issue #458. This is already fixed in the latest image. Re-pull the image.

**Closed** 2024-10-06 14:31 UTC
Labels: duplicate
