### ISSUE TITLE
LATEST version not found, PREVIOUS works

### ISSUE THREAD

**Issue by dabadgreek** [itzg/docker-minecraft-bedrock-server#170] opened 2021-07-27 19:05 UTC
Hello,

Recently I keep getting the following errors when I am trying to run the docker container with 'LATEST' version. 

Failed to extract download URL '' from https://www.minecraft.net/en-us/download/server/bedrock/
2021/07/27 18:23:50 Unable to find an element with attribute matcher data-platform=serverBedrockLinux

If I use 'PREVIOUS' it loads version "1.13.0.34" and runs just fine. This has been working for over a year, wondering what I am doing wrong.

Thanks,
Steve

**Comment by itzg** [comment] 2021-07-27 21:26
Seems to be a duplicate of #155. Please make sure you have pulled the latest image.

**Closed** 2021-08-10 22:06 UTC
Labels: duplicate, status/waiting on feedback
