### ISSUE TITLE
Starting via Stack - immediately crashes

### ISSUE THREAD

**Issue by eytschjey** [itzg/docker-minecraft-bedrock-server#259] opened 2022-07-02 06:30 UTC
This is my docker-compose in Portainer:
`version: "3.8"
services:
  bedrock_server:
    image: itzg/minecraft-bedrock-server
    ports:
      - "19132:19132/udp"
    environment:
      EULA: "TRUE"
      SERVER_NAME: mineserv
      ONLINE_MODE: "true"
      SERVER_PORT: 19132
      GAMEMODE: survival
      DIFFICULTY: normal
      DEBUG: "true"
    volumes:
      - /home/jan/docker/minecraft:/data
    tty: true
    stdin_open: true`

Upon start, the container immediately stops. These are the logs:

`} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x5629150905c0)
} [5 bytes data]
> GET /bin-linux/bedrock-server-1.19.2.02.zip HTTP/2

> Host: minecraft.azureedge.net

> user-agent: curl/7.74.0

> accept: */*

> 

{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [265 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [265 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
} [5 bytes data]
< HTTP/2 200 

< content-length: 72204228

< content-type: application/octet-stream

< content-md5: ia4Ra9dwa7+lhXC0Za25+g==

< last-modified: Wed, 22 Jun 2022 15:47:43 GMT

< accept-ranges: bytes

< etag: "0x8DA54668BE90FE6"

< server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0

< x-ms-request-id: 8f53a679-801e-0076-0153-86b26a000000

< x-ms-version: 2014-02-14

< x-ms-lease-status: unlocked

< x-ms-lease-state: available

< x-ms-blob-type: BlockBlob

< date: Sat, 02 Jul 2022 06:26:40 GMT

< 

{ [6831 bytes data]
* Connection #0 to host minecraft.azureedge.net left intact
+ rm -rf bedrock_server 'bedrock_server-*' '*.so' release-notes.txt bedrock_server_how_to.html valid_known_packs.json premium_cache
+ bkupDir=backup-pre-1.19.2.02
+ rm -rf backup-pre-1.19.2.02
+ for d in behavior_packs definitions minecraftpe resource_packs structures treatments world_templates
+ '[' -d behavior_packs ']'
+ for d in behavior_packs definitions minecraftpe resource_packs structures treatments world_templates
+ '[' -d definitions ']'
+ for d in behavior_packs definitions minecraftpe resource_packs structures treatments world_templates
+ '[' -d minecraftpe ']'
+ for d in behavior_packs definitions minecraftpe resource_packs structures treatments world_templates
+ '[' -d resource_packs ']'
+ for d in behavior_packs definitions minecraftpe resource_packs structures treatments world_templates
+ '[' -d structures ']'
+ for d in behavior_packs definitions minecraftpe resource_packs structures treatments world_templates
+ '[' -d treatments ']'
+ for d in behavior_packs definitions minecraftpe resource_packs structures treatments world_templates
+ '[' -d world_templates ']'
+ ((  2 >= 0  ))
+ shopt -s nullglob
++ ls -td1
++ tail +3
+ unzip -q -n /tmp/bedrock-server-1.19.2.02.zip
+ [[ /tmp != /tmp ]]
+ chmod +x bedrock_server
+ mv bedrock_server bedrock_server-1.19.2.02
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ allowListUsers=
+ '[' -n '' ']'
+ set-property --file server.properties --bulk /etc/bds-property-definitions.json
2022/07/02 06:26:44 Setting server-name to mineserv in server.properties
2022/07/02 06:26:44 Setting difficulty to normal in server.properties
+ export LD_LIBRARY_PATH=.
+ LD_LIBRARY_PATH=.
+ echo 'Starting Bedrock server...'
+ exec ./bedrock_server-1.19.2.02
Starting Bedrock server...
NO LOG FILE! - setting up server logging...
[2022-07-02 06:26:44:685 INFO] Starting Server
[2022-07-02 06:26:44:685 INFO] Version 1.19.2.02
[2022-07-02 06:26:44:685 INFO] Session ID 2123f332-0b47-4d45-ac3f-a4460e2b1484
[2022-07-02 06:26:44:685 INFO] Level Name: Bedrock level
[2022-07-02 06:26:44:686 INFO] Game mode: 0 Survival
[2022-07-02 06:26:44:686 INFO] Difficulty: 2 NORMAL
[2022-07-02 06:26:44:713 INFO] opening worlds/Bedrock level/db
terminate called without an active exception
[2022-07-02 06:26:44:074 ERROR] Network port occupied, can't start server.
[2022-07-02 06:26:44:074 INFO] Server stop requested.
[2022-07-02 06:26:44:108 INFO] Package: com.mojang.minecraft.dedicatedserver
Version: 1.19.2.02
OS: Linux
Server start: 2022-07-02 06:26:44 UTC
Dmp timestamp: 2022-07-02 06:26:44 UTC
Upload Date: 2022-07-02 06:26:44 UTC
Session ID: 2123f332-0b47-4d45-ac3f-a4460e2b1484
Commit hash: b3394b7158e4fbb6c99df8addd52f13420b1dcf8
Build id: 10134919
CrashReporter Key: 8c4937c1-64cb-3532-a8dc-1deb28f67293

Crash
[2022-07-02 06:26:44:108 INFO] 	at gsignal (UnknownFile:?)
	at abort (UnknownFile:?)
	at __libc_start_main (UnknownFile:?)
Failed to open curl lib from binary, use libcurl.so instead
`
I already forwarded Port 19132 in my router, what am i doing wrong?

**Comment by itzg** [comment] 2022-07-02 13:14
This is a duplicate of #149

**Closed** 2022-07-02 13:14 UTC
