### ISSUE TITLE
LATEST not updating on server restart

### ISSUE THREAD

**Issue by MemoryOverlord** [itzg/docker-minecraft-bedrock-server#160] opened 2021-07-14 02:14 UTC
Fairly new to running a Minecraft server, so forgive my ignorance...

Have been using your Docker container for about a month with no issues. This morning my Xbox received the Minecraft 1.17.10 update. I restarted the server (multiple times) but it continues to run the June 2021 update (1.17.2).

If I use "Duplicate/Edit" to force the update, will everything my friends and I have created been lost?

**Comment by MemoryOverlord** [comment] 2021-07-14 02:28
Found this in the logs of 2 of the 3 Bedrock servers I am running

WARN Minecraft download page failed, so using existing download of 1.17.2.01

All three Docker containers were created identical to each other with the exception of the seed number. Yet only one of them has updated correctly.

**Comment by itzg** [comment] 2021-07-14 02:30
Duplicate of #155 however I do find it odd it's not consistently failing across all three.

**Closed by itzg** 2021-07-14 02:30 UTC

**Comment by MemoryOverlord** [comment] 2021-07-14 02:42
Crap, I didn't see #155 ... however, my additional question remains, "If I use "Duplicate/Edit" to force the update, will everything my friends and I have created been lost?"

**Comment by itzg** [comment] 2021-07-14 02:48
I'm not sure what you mean by duplicate/edit. Are you using a Docker management UI? In any case, as long as you reattach the same data volume nothing will be lost.

**Comment by MemoryOverlord** [comment] 2021-07-14 03:11
Yes, I use Portainer.

As mentioned above, this is new to me
