### ISSUE TITLE
Minecraft download page failed

### ISSUE THREAD

**Issue by djryan012** [itzg/docker-minecraft-bedrock-server#159] opened 2021-07-14 01:12 UTC
Just tried restarting my docker image and got this in the log. Not able to download latest version of MC Bedrock. Here is my docker log from termination and restart of image

DEBU[0305] Forwarding signal                             signal=terminated
DEBU[0305] Sending message on stdin due to SIGTERM       message=stop
[INFO] Server stop requested.
[INFO] Stopping server...
Quit correctly
DEBU[0000] Using /data to match uid and gid             
DEBU[0000] Resolved UID=999 from match path             
DEBU[0000] Resolved GID=999 from match path             
WARN Minecraft download page failed, so using existing download of 1.17.2.01
2021/07/14 01:07:23 Unable to find an element with attribute matcher data-platform=serverBedrockLinux
Starting Bedrock server...
NO LOG FILE! - Failed to up file descriptor limit Operation not permitted
NO LOG FILE! - setting up server logging...
[2021-07-14 01:07:23 INFO] Starting Server
[2021-07-14 01:07:23 INFO] Version 1.17.2.01
[2021-07-14 01:07:23 INFO] Session ID (removed id for security)
[2021-07-14 01:07:23 INFO] Level Name: Mark and Davids
[2021-07-14 01:07:23 INFO] Game mode: 0 Survival
[2021-07-14 01:07:23 INFO] Difficulty: 2 NORMAL
[INFO] opening worlds/Mark and Davids/db
[INFO] IPv4 supported, port: 19132
[INFO] IPv6 not supported
[INFO] IPv4 supported, port: 37709
[INFO] IPv6 not supported
[INFO] Server started.

**Comment by itzg** [comment] 2021-07-14 01:21
Duplicate of #155 but also make sure you have pulled the latest image.

**Closed by itzg** 2021-07-14 01:21 UTC
